<div class="foto" id="foto">
	TTTTT
</div>
	
<div class="detalles" id="detalles">
	<div class="titulo">Titulo</div>
	<div class="texto">Texto </div>

	
	<div class="galeria">
		<img src="http://congenital-heart-defects.co.uk/images/atrialseptaldefect3.jpeg" height="64px" width="64px" />
	</div>
	<div class="galeria">
		<img src="http://congenital-heart-defects.co.uk/images/atrialseptaldefect3.jpeg" height="64px" width="64px" />
	</div>
	<div class="galeria">
		<img src="http://congenital-heart-defects.co.uk/images/atrialseptaldefect3.jpeg" height="64px" width="64px" />
	</div>
	<div class="galeria">
		<img src="http://congenital-heart-defects.co.uk/images/atrialseptaldefect3.jpeg" height="64px" width="64px" />
	</div>
	<div class="galeria">
		<img src="http://congenital-heart-defects.co.uk/images/atrialseptaldefect3.jpeg" height="64px" width="64px" />
	</div>
	<div class="galeria">
		<img src="http://congenital-heart-defects.co.uk/images/atrialseptaldefect3.jpeg" height="64px" width="64px" />
	</div>
	<div class="galeria">
		<img src="http://congenital-heart-defects.co.uk/images/atrialseptaldefect3.jpeg" height="64px" width="64px" />
	</div><div class="galeria">
		<img src="http://congenital-heart-defects.co.uk/images/atrialseptaldefect3.jpeg" height="64px" width="64px" />
	</div>
	<div class="galeria">
		<img src="http://congenital-heart-defects.co.uk/images/atrialseptaldefect3.jpeg" height="64px" width="64px" />
	</div>
	<div class="galeria">
		<img src="http://congenital-heart-defects.co.uk/images/atrialseptaldefect3.jpeg" height="64px" width="64px" />
	</div>
	
</div>
	
<div class="video" id="video">
		video
</div>

<div class="productos" id="productos">
		otros productos
</div>


	
