<div id="mainhome">
	<center>
	<div id="login">
		<form action="/systemhome/" method="POST">
			<div style="height:50px;">
				<div style="float:left;width:80px;">Nombre:</div>
				<div style="float:left;width:100px;"><input type="text" name="user" /></div>
			</div>
			<div style="height:50px;">
				<div style="float:left;width:80px;">Pass:</div>
				<div style="float:left;width:100px;"><input type="password" name="pass" /></div>
			</div>
			<div style="height:50px;text-align:left;">
				<input type="submit" id="button" style="height:50px;width:200px;margin-left:50px;" name="login" value="Enviar"/>
			</div>
		</form>
	</div>
	</center>
</div>